version: '3.8'

services:
  dac-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dac-app
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB:-dacdb}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION:-usuarios}
      PY_BACKEND_PORT: 5000
      SEED_ON_START: ${SEED_ON_START:-false}
    ports:
      - "3000:3000"   # frontend
      - "5000:5000"   # backend
    restart: unless-stopped
    networks:
      - dac-network

networks:
  dac-network:
    driver: bridge
